# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#
#Makefile for the Smart card driver.
#
MODULE_NAME = amsmc_sc2

obj-$(CONFIG_AMLOGIC_SMARTCARD) = $(MODULE_NAME).o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_SMARTCARD) += smartcard.o
